In [1]:
import numpy as np

In [4]:
np.random.uniform(low=0, high=1, size=3)

array([0.24013814, 0.07167224, 0.66380823])

In [44]:
sigma = np.random.uniform(size=2)
mu = np.random.uniform(size=2)
y = np.array([1, 2, 3, 4, 5, 6]).reshape([-1,1])
y = np.concatenate((y, y), axis=1)
sigma, mu, y

(array([0.93029861, 0.46159661]),
 array([0.89705003, 0.67523321]),
 array([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6]]))

In [45]:
1 / (np.sqrt(2 * np.pi) * sigma)

array([0.4288325 , 0.86426605])

In [48]:
phi = (1 / (np.sqrt(2 * np.pi) * sigma)) * np.exp((- (y - mu) ** 2) / (2 * sigma ** 2))
phi

array([[4.26214704e-01, 6.74770986e-01],
       [2.12354722e-01, 1.40627141e-02],
       [3.33184751e-02, 2.68363971e-06],
       [1.64625843e-03, 4.68944647e-12],
       [2.56153685e-05, 7.50345478e-20],
       [1.25514212e-07, 1.09936845e-29]])

In [49]:
a = np.array([0, 1])

In [50]:
phi * a

array([[0.00000000e+00, 6.74770986e-01],
       [0.00000000e+00, 1.40627141e-02],
       [0.00000000e+00, 2.68363971e-06],
       [0.00000000e+00, 4.68944647e-12],
       [0.00000000e+00, 7.50345478e-20],
       [0.00000000e+00, 1.09936845e-29]])

In [57]:
phi * a / (phi.sum(axis=1) * np.array([1, 2, 3, 4, 5, 6])).reshape([-1, 1])

array([[0.00000000e+00, 6.12878980e-01],
       [0.00000000e+00, 3.10548392e-02],
       [0.00000000e+00, 2.68462023e-05],
       [0.00000000e+00, 7.12137045e-10],
       [0.00000000e+00, 5.85855697e-16],
       [0.00000000e+00, 1.45981935e-23]])

In [60]:
phi.sum(axis=0)

array([0.6735599 , 0.68883638])

In [64]:
y = np.array([1, 2, 3, 4, 5, 6]).reshape([-1,1])

In [66]:
phi

array([[4.26214704e-01, 6.74770986e-01],
       [2.12354722e-01, 1.40627141e-02],
       [3.33184751e-02, 2.68363971e-06],
       [1.64625843e-03, 4.68944647e-12],
       [2.56153685e-05, 7.50345478e-20],
       [1.25514212e-07, 1.09936845e-29]])

In [67]:
(phi * y).sum(axis=0) / phi.sum(axis=0)

array([1.42169009, 1.02042297])

In [70]:
phi * y

array([[4.26214704e-01, 6.74770986e-01],
       [4.24709443e-01, 2.81254282e-02],
       [9.99554253e-02, 8.05091912e-06],
       [6.58503372e-03, 1.87577859e-11],
       [1.28076842e-04, 3.75172739e-19],
       [7.53085272e-07, 6.59621070e-29]])

In [72]:
y

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [75]:
mu

array([0.89705003, 0.67523321])

In [78]:
phi * (y - mu) ** 2

array([[4.51732038e-03, 7.11704365e-02],
       [2.58329230e-01, 2.46801624e-02],
       [1.47347577e-01, 1.45038398e-05],
       [1.58506676e-02, 5.18374893e-11],
       [4.31214197e-04, 1.40341675e-18],
       [3.26840243e-06, 3.11705491e-28]])

In [80]:
np.linalg.norm(np.concatenate([mu, sigma]))

1.5294330866737194