In [1]:
from sklearn.datasets import load_iris
from logistic import logisticRegression
import numpy as np

In [2]:
load = load_iris()

In [3]:
x = load.data[:100,:2]
y = load.target[:100].reshape(100, 1)

In [4]:
x.shape

(100, 2)

In [5]:
y.shape

(100, 1)

In [6]:
lgr = logisticRegression()

In [7]:
data = np.concatenate([x, y], axis=1)
data

array([[5.1, 3.5, 0. ],
       [4.9, 3. , 0. ],
       [4.7, 3.2, 0. ],
       [4.6, 3.1, 0. ],
       [5. , 3.6, 0. ],
       [5.4, 3.9, 0. ],
       [4.6, 3.4, 0. ],
       [5. , 3.4, 0. ],
       [4.4, 2.9, 0. ],
       [4.9, 3.1, 0. ],
       [5.4, 3.7, 0. ],
       [4.8, 3.4, 0. ],
       [4.8, 3. , 0. ],
       [4.3, 3. , 0. ],
       [5.8, 4. , 0. ],
       [5.7, 4.4, 0. ],
       [5.4, 3.9, 0. ],
       [5.1, 3.5, 0. ],
       [5.7, 3.8, 0. ],
       [5.1, 3.8, 0. ],
       [5.4, 3.4, 0. ],
       [5.1, 3.7, 0. ],
       [4.6, 3.6, 0. ],
       [5.1, 3.3, 0. ],
       [4.8, 3.4, 0. ],
       [5. , 3. , 0. ],
       [5. , 3.4, 0. ],
       [5.2, 3.5, 0. ],
       [5.2, 3.4, 0. ],
       [4.7, 3.2, 0. ],
       [4.8, 3.1, 0. ],
       [5.4, 3.4, 0. ],
       [5.2, 4.1, 0. ],
       [5.5, 4.2, 0. ],
       [4.9, 3.1, 0. ],
       [5. , 3.2, 0. ],
       [5.5, 3.5, 0. ],
       [4.9, 3.6, 0. ],
       [4.4, 3. , 0. ],
       [5.1, 3.4, 0. ],
       [5. , 3.5, 0. ],
       [4.5, 2.3

In [9]:
lgr.fit(data)

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

In [143]:
lgr.w

In [142]:
lgr.predict(data[:,:-1])

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

In [45]:
w = np.array([2, 2, 2, 2, 2])

In [46]:
w

array([2, 2, 2, 2, 2])

In [47]:
a

array([[1., 2., 3., 4., 1.],
       [2., 3., 4., 5., 1.],
       [3., 4., 5., 6., 1.]])

In [50]:
w * a

array([[ 2.,  4.,  6.,  8.,  2.],
       [ 4.,  6.,  8., 10.,  2.],
       [ 6.,  8., 10., 12.,  2.]])

In [49]:
np.sum(w * a, axis=1)

array([22., 30., 38.])

In [70]:
y = np.array([0, 1,1]).reshape(3, 1)

In [71]:
a * y

array([[0., 0., 0., 0., 0.],
       [2., 3., 4., 5., 1.],
       [3., 4., 5., 6., 1.]])

In [54]:
a[:, -1].shape

(3,)

In [56]:
y.shape

(3,)

In [74]:
def exp(w, x):
    return np.exp(np.sum(w * x, axis=1))

In [90]:
tmp = a*y - (exp(w, a) / (1 + exp(w, a))).reshape(3,1)
tmp

array([[-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
        -1.0000000e+00],
       [ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00,  4.0000000e+00,
         9.3591801e-14],
       [ 2.0000000e+00,  3.0000000e+00,  4.0000000e+00,  5.0000000e+00,
         0.0000000e+00]])

In [92]:
g = np.sum(w * tmp, axis=0)
g

array([ 4.,  8., 12., 16., -2.])

In [78]:
exp(w, a)

array([3.58491285e+09, 1.06864746e+13, 3.18559318e+16])

In [93]:
w - 0.5 * g

array([-2.79040346e-10, -2.00000000e+00, -4.00000000e+00, -6.00000000e+00,
        3.00000000e+00])

In [122]:
t = np.array([1, 2, 1,2,1,2,2, 2]).reshape(2, 4)
t

array([[1, 2, 1, 2],
       [1, 2, 2, 2]])

In [115]:
np.unique(t)

array([1, 2])

In [120]:
d = {1: 0, 2: 1}
d

{1: 0, 2: 1}

In [123]:
t = np.array([d[i] for i in t.flatten()]).reshape(t.shape)
t

array([[0, 1, 0, 1],
       [0, 1, 1, 1]])

In [112]:
for i in t.flatten():
    print(i)

1
2
1
2
1
2
2
2


In [124]:
p1 = np.array([1, 1, 1, 1, 1])
p2 = np.array([2, 0, 2, 1, 0])

In [127]:
(p1 > p2).astype(int)

array([0, 1, 0, 0, 1])