In [1]:
class A:

    def __init__(self, x) -> None:
        self.x = x

In [2]:
def t(a: A):
    r = []
    for i in range(10):
        r.append(a(i))
    return r

In [3]:
r = t(A)

In [4]:
for a in r:
    print(a.x)

0
1
2
3
4
5
6
7
8
9


In [16]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

In [8]:
(a * b).sum()

20

In [10]:
c = np.array(
[]
)

In [14]:
c = np.append(c, 1)

In [15]:
c

array([1.])

In [17]:
a = np.array([1, 1, 1, 1, 1, -1, -1, -1, -1, -1])

In [18]:
values = np.unique(a)
values

array([-1,  1])

In [19]:
c = np.array([a[a==v].shape[0] for v in values])
c

array([5, 5])

In [21]:
x = c / a.shape[0]
x

array([0.5, 0.5])

In [22]:
x = np.where(x == 0, 1, x)
x

array([0.5, 0.5])

In [23]:
(-x * np.log2(x)).sum()

1.0

In [24]:
np.log2(x)

array([-1., -1.])

In [25]:
x * np.log2(x)

array([-0.5, -0.5])

In [26]:
a = np.array([])

In [27]:
np.append(a, 1)

array([1.])

In [28]:
a

array([], dtype=float64)

In [29]:
a = np.array([[1, 2], [3, 4]])

In [30]:
a

array([[1, 2],
       [3, 4]])

In [31]:
a[:, 1]

array([2, 4])