In [1]:
from sklearn.datasets import load_wine
import numpy as np
import pandas as pd

# 数据集
使用sklearn中的红酒数据集

In [2]:
wine = load_wine()
names = wine.feature_names + ['target']
wine = pd.concat([pd.DataFrame(wine.data),pd.DataFrame(wine.target)],axis=1)
wine.columns = names
wine.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [3]:
a = list(wine.columns)
a.pop(13)
a

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [4]:
wine.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'target'],
      dtype='object')

In [5]:
wine

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [6]:
wine.groupby('alcohol').count

<bound method GroupBy.count of <pandas.core.groupby.generic.DataFrameGroupBy object at 0x16c0884a0>>

In [7]:
data = pd.read_csv("/Users/0g/Documents/2425s/learning/统计学习算法/5.决策树/data1.csv", header=0, index_col=0)

In [8]:
data

年龄 有工作 有房子 信贷情况 类别
ID                    
1   青年   否   否   一般  否
2   青年   否   否    好  否
3   青年   是   否    好  是
4   青年   是   是   一般  是
5   青年   否   否   一般  否
6   中年   否   否   一般  否
7   中年   否   否    好  否
8   中年   是   是    好  是
9   中年   否   是  非常好  是
10  中年   否   是  非常好  是
11  老年   否   是  非常好  是
12  老年   否   是    好  是
13  老年   是   否    好  是
14  老年   是   否  非常好  是
15  老年   否   否   一般  否

In [9]:
data.columns

Index(['年龄', '有工作', '有房子', '信贷情况', '类别'], dtype='object')

In [10]:
tmp = data.groupby('类别').count().iloc[:, 0].to_numpy()
tmp

array([6, 9])

In [11]:
np.array([tmp.iloc[i, 0] for i in range(len(tmp))]) / 15

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

In [72]:
h = tmp / 15
h

array([0.4, 0.6])

In [75]:
(-h * (np.log2(h))).sum()

0.9709505944546686

In [77]:
tmp = data.groupby('年龄').count()
tmp

有工作  有房子  信贷情况  类别
年龄                    
中年    5    5     5   5
老年    5    5     5   5
青年    5    5     5   5

In [78]:
list(tmp.index)

['中年', '老年', '青年']

In [82]:
data

年龄 有工作 有房子 信贷情况 类别
ID                    
1   青年   否   否   一般  否
2   青年   否   否    好  否
3   青年   是   否    好  是
4   青年   是   是   一般  是
5   青年   否   否   一般  否
6   中年   否   否   一般  否
7   中年   否   否    好  否
8   中年   是   是    好  是
9   中年   否   是  非常好  是
10  中年   否   是  非常好  是
11  老年   否   是  非常好  是
12  老年   否   是    好  是
13  老年   是   否    好  是
14  老年   是   否  非常好  是
15  老年   否   否   一般  否

In [89]:
tmp = data[data['类别']=='是']
tmp

年龄 有工作 有房子 信贷情况 类别
ID                    
3   青年   是   否    好  是
4   青年   是   是   一般  是
8   中年   是   是    好  是
9   中年   否   是  非常好  是
10  中年   否   是  非常好  是
11  老年   否   是  非常好  是
12  老年   否   是    好  是
13  老年   是   否    好  是
14  老年   是   否  非常好  是

In [91]:
len(tmp[tmp['年龄']=='青年'])

2

In [20]:
from utils import get_all_count, entropy

In [9]:
a = get_all_count(data, '类别')['年龄']
a

array([[2., 1., 3.],
       [3., 4., 2.]])

In [11]:
b = a.sum(axis=0)
b

array([5., 5., 5.])

In [16]:
c = a / b
c

array([[0.4, 0.2, 0.6],
       [0.6, 0.8, 0.4]])

In [17]:
c[:, 0]

array([0.4, 0.6])

In [22]:
d = [entropy(c[:,i]) for i in range(a.shape[1])]
d

[0.9709505944546686, 0.7219280948873623, 0.9709505944546686]

In [24]:
(d * b / 15).sum()

0.8879430945988998

In [31]:
test = np.array([0,0.12131,0.42])
test

array([0.     , 0.12131, 0.42   ])

In [34]:
x = -test
x = np.maximum(x, -1)
x = -x

In [35]:
x

array([0.     , 0.12131, 0.42   ])

In [29]:
np.where(test == 0, 1, )

array([1, 1, 1])

In [30]:
np.log2(0)

/var/folders/gd/k10zntz95lj0m0mpzg54z14w0000gn/T/ipykernel_3756/2251961259.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(0)


-inf

In [24]:
np.argmax(data.groupby('类别').count().iloc[:,0].to_numpy())

1

In [18]:
tmp = data[data['类别']=='是']
list(tmp.groupby('类别').count().index)

['是']

In [25]:
a = {'年龄': 0.08300749985576883, '有工作': 0.32365019815155616, '有房子': 0.4199730940219748, '信贷情况': 0.36298956253708536}

In [26]:
a

{'年龄': 0.08300749985576883,
 '有工作': 0.32365019815155616,
 '有房子': 0.4199730940219748,
 '信贷情况': 0.36298956253708536}

In [32]:
b = list(zip(a.keys(), a.values()))
b

[('年龄', 0.08300749985576883),
 ('有工作', 0.32365019815155616),
 ('有房子', 0.4199730940219748),
 ('信贷情况', 0.36298956253708536)]

In [38]:
b.sort(key=lambda x: x[1], reverse=True)

In [39]:
b

[('有房子', 0.4199730940219748),
 ('信贷情况', 0.36298956253708536),
 ('有工作', 0.32365019815155616),
 ('年龄', 0.08300749985576883)]

In [40]:
data

年龄 有工作 有房子 信贷情况 类别
ID                    
1   青年   否   否   一般  否
2   青年   否   否    好  否
3   青年   是   否    好  是
4   青年   是   是   一般  是
5   青年   否   否   一般  否
6   中年   否   否   一般  否
7   中年   否   否    好  否
8   中年   是   是    好  是
9   中年   否   是  非常好  是
10  中年   否   是  非常好  是
11  老年   否   是  非常好  是
12  老年   否   是    好  是
13  老年   是   否    好  是
14  老年   是   否  非常好  是
15  老年   否   否   一般  否

In [41]:
data.drop(columns=['年龄'])

有工作 有房子 信贷情况 类别
ID                
1    否   否   一般  否
2    否   否    好  否
3    是   否    好  是
4    是   是   一般  是
5    否   否   一般  否
6    否   否   一般  否
7    否   否    好  否
8    是   是    好  是
9    否   是  非常好  是
10   否   是  非常好  是
11   否   是  非常好  是
12   否   是    好  是
13   是   否    好  是
14   是   否  非常好  是
15   否   否   一般  否

In [47]:
s = data[data['类别'] == '是']
s

年龄 有工作 有房子 信贷情况 类别
ID                    
3   青年   是   否    好  是
4   青年   是   是   一般  是
8   中年   是   是    好  是
9   中年   否   是  非常好  是
10  中年   否   是  非常好  是
11  老年   否   是  非常好  是
12  老年   否   是    好  是
13  老年   是   否    好  是
14  老年   是   否  非常好  是

In [48]:
s.index

Index([3, 4, 8, 9, 10, 11, 12, 13, 14], dtype='int64', name='ID')

In [49]:
data.loc[s.index]

年龄 有工作 有房子 信贷情况 类别
ID                    
3   青年   是   否    好  是
4   青年   是   是   一般  是
8   中年   是   是    好  是
9   中年   否   是  非常好  是
10  中年   否   是  非常好  是
11  老年   否   是  非常好  是
12  老年   否   是    好  是
13  老年   是   否    好  是
14  老年   是   否  非常好  是

In [53]:
tmp = data.groupby('类别').count().iloc[:, 0].to_numpy()
tmp

array([6, 9])

In [54]:
tmp / tmp.sum()

array([0.4, 0.6])

In [55]:
a = [1, 2, 3]
sum(a)

6

In [56]:
class a:

    def __init__(self, i) -> None:
        self.i = i

In [60]:
l = [a(i) for i in range(5)]

In [61]:
b = l[0]

In [62]:
b in l

True

In [63]:
b in l.copy()

True

In [64]:
l[0] = 1

In [65]:
b

In [66]:
b in l

False

In [67]:
a = []
b = [1, 2]
c = []

In [69]:
a += b
a

[1, 2]